#import "../config/commands.typ": front-heading

#front-heading[TÓM TẮT]

Trong công tác quản trị và thực hành mạng máy tính, cấu hình thiết bị qua giao diện dòng lệnh (CLI) thường đòi hỏi nhiều thao tác lặp lại, tiềm ẩn lỗi cú pháp và gây khó khăn khi kiểm soát sai lệch cấu hình. Để khắc phục những hạn chế đó, đề tài xây dựng CAMS, một hệ thống hỗ trợ quản lý tập trung, tự động hóa cấu hình và giám sát an ninh mạng cho thiết bị Cisco IOS trong môi trường học tập và thực nghiệm.

CAMS được thiết kế theo kiến trúc phân lớp, kết hợp giao diện khai báo bằng Qt Quick/QML, lớp điều phối PyQt6, hai cơ sở dữ liệu SQLite phân biệt cấu hình và dữ liệu quan sát, các tác vụ nền sử dụng Netmiko/Paramiko và bộ tạo mẫu Jinja2. Hệ thống vận hành theo quy trình quản trị dựa trên trạng thái: quản lý danh mục thiết bị, thu thập và sao lưu `running-config` vào kho Git cục bộ bằng Dulwich, xác lập cấu hình mong muốn, kiểm duyệt lệnh rồi triển khai xuống thiết bị.

Phạm vi của CAMS bao gồm chuyển mạch Lớp 2, định tuyến và các dịch vụ Lớp 3. Hệ thống còn tích hợp bộ thu nhận Syslog, máy khách dùng giao thức truyền tệp qua SSH (SSH File Transfer Protocol – SFTP) và đầu cuối nhúng phục vụ thao tác dòng lệnh. Năm kịch bản thử nghiệm bao gồm DHCP Snooping/DAI, OSPF, GLBP–DHCP–NAT/PAT, Syslog và ACL. Kịch bản 1 ghi nhận DAI chặn bản tin ARP không khớp liên kết DHCP; kịch bản 5 ghi nhận lưu lượng bị ACL từ chối, lưu lượng đối chứng được phép và nhật ký tương ứng. Trong kịch bản OSPF một vùng trên năm bộ định tuyến, sáu phép thử ICMP giữa ba cặp máy trạm đều nhận đủ 5/5 hồi đáp trong mỗi loạt thử. Ảnh chụp bộ nhận Syslog ghi nhận 245 bản tin tại thời điểm quan sát. Các số liệu này mô tả những phép quan sát cụ thể, chưa xác định tỷ lệ thành công dài hạn, thông lượng hoặc mức cải thiện thời gian so với CLI thủ công.
