#import "../config/commands.typ": front-heading
#import "../config/tables.typ": report-table

#front-heading[DANH MỤC TỪ VIẾT TẮT]

#set par(justify: false)
#table(
  columns: (15%, 35%, 50%),
  align: left + horizon,
  stroke: 0.5pt,
  table.header(
    [*Từ viết tắt*], [*Tên đầy đủ*], [*Ý nghĩa*]
  ),
  [ABR], [Area Border Router], [Router biên giữa các vùng trong OSPF],
  [ACL], [Access Control List], [Danh sách kiểm soát truy cập],
  [AES], [Advanced Encryption Standard], [Tiêu chuẩn mã hóa nâng cao],
  [API], [Application Programming Interface], [Giao diện lập trình ứng dụng],
  [ARP], [Address Resolution Protocol], [Giao thức phân giải địa chỉ IPv4 sang địa chỉ MAC],
  [AS], [Autonomous System], [Hệ thống tự trị trong định tuyến],
  [ASBR], [Autonomous System Boundary Router], [Router biên hệ tự trị trong OSPF],
  [BGP], [Border Gateway Protocol], [Giao thức định tuyến liên miền],
  [CLI], [Command-Line Interface], [Giao diện dòng lệnh],
  [CRUD], [Create, Read, Update, Delete], [Nhóm thao tác cơ bản trên dữ liệu],
  [DAI], [Dynamic ARP Inspection], [Kiểm tra tính hợp lệ của gói tin ARP],
  [DHCP], [Dynamic Host Configuration Protocol], [Giao thức cấp phát cấu hình IP động],
  [DNS], [Domain Name System], [Hệ thống phân giải tên miền],
  [DPAPI], [Data Protection Application Programming Interface], [Giao diện bảo vệ dữ liệu trên Windows],
  [EIGRP], [Enhanced Interior Gateway Routing Protocol], [Giao thức định tuyến cổng nội bộ nâng cao],
  [ERD], [Entity–Relationship Diagram], [Sơ đồ thực thể – quan hệ trong thiết kế cơ sở dữ liệu],
  [FHRP], [First Hop Redundancy Protocol], [Giao thức mạng cung cấp tính năng dự phòng cho default gateway],
  [GCM], [Galois/Counter Mode], [Chế độ mã hóa xác thực AES-GCM],
  [GLBP], [Gateway Load Balancing Protocol], [Giao thức dự phòng gateway kết hợp cân bằng tải của Cisco],
  [GRE], [Generic Routing Encapsulation], [Giao thức đóng gói đường hầm mạng],
  [GUI], [Graphical User Interface], [Giao diện đồ họa người dùng],
  [HSRP], [Hot Standby Router Protocol], [Giao thức dự phòng gateway của Cisco, kết hợp nhiều router vật lý thành một router ảo duy nhất],
  [IaC], [Infrastructure as Code], [Quản lý hạ tầng bằng mã],
  [ICMP], [Internet Control Message Protocol], [Giao thức kiểm soát bản tin Internet],
  [IOS], [Internetwork Operating System], [Hệ điều hành mạng của thiết bị Cisco],
  [IPC], [Inter-Process Communication], [Giao tiếp giữa các tiến trình],
  [ISP], [Internet Service Provider], [Nhà cung cấp dịch vụ Internet],
  [JSON], [JavaScript Object Notation], [Định dạng trao đổi dữ liệu nhẹ dạng văn bản],
  [LACP], [Link Aggregation Control Protocol], [Giao thức điều khiển gom kênh liên kết],
  [LAN], [Local Area Network], [Mạng cục bộ],
  [LSA], [Link State Advertisement], [Gói quảng bá trạng thái liên kết trong OSPF],
  [MAC], [Media Access Control], [Địa chỉ điều khiển truy cập phương tiện Lớp 2],
  [NAT], [Network Address Translation], [Biên dịch địa chỉ mạng],
  [NTP], [Network Time Protocol], [Giao thức đồng bộ thời gian qua mạng],
  [OSPF], [Open Shortest Path First], [Giao thức định tuyến chọn đường ngắn nhất],
  [PAgP], [Port Aggregation Protocol], [Giao thức gom cổng độc quyền của Cisco],
  [PAT], [Port Address Translation], [Biên dịch địa chỉ theo cổng, còn gọi là NAT Overload],
  [QML], [Qt Modeling Language], [Ngôn ngữ mô tả giao diện khai báo Qt Quick],
  [RSTP], [Rapid Spanning Tree Protocol], [Giao thức cây bao trùm hội tụ nhanh],
  [SFTP], [SSH File Transfer Protocol], [Giao thức truyền tệp an toàn qua SSH],
  [SHA], [Secure Hash Algorithm], [Thuật toán băm an toàn],
  [SSH], [Secure Shell], [Giao thức truy cập từ xa có mã hóa],
  [STP], [Spanning Tree Protocol], [Giao thức cây bao trùm chống vòng lặp L2],
  [SVI], [Switch Virtual Interface], [Cổng ảo Lớp 3 trên thiết bị Switch],
  [TCP], [Transmission Control Protocol], [Giao thức truyền tải hướng kết nối],
  [TTL], [Time To Live], [Thời gian sống của gói tin IP],
  [UDP], [User Datagram Protocol], [Giao thức truyền tải không kết nối],
  [VLAN], [Virtual Local Area Network], [Mạng cục bộ ảo Lớp 2],
  [VPC], [Virtual PC], [Máy tính cá nhân ảo dùng trong môi trường mô phỏng mạng],
  [VRF], [Virtual Routing and Forwarding], [Bảng định tuyến ảo hóa độc lập trên cùng thiết bị],
  [VRRP], [Virtual Router Redundancy Protocol], [Giao thức dự phòng router ảo chuẩn IEEE],
  [VTP], [VLAN Trunking Protocol], [Giao thức đồng bộ cấu hình VLAN],
)
