#import "../config/commands.typ": front-heading
#import "../config/tables.typ": report-table

#front-heading[DANH MỤC TỪ VIẾT TẮT]

#set par(justify: false)
#table(
  columns: (15%, 35%, 50%),
  align: left + horizon,
  stroke: 0.5pt,
  table.header(
    [*Từ viết tắt*], [*Tên đầy đủ*], [*Ý nghĩa*]
  ),
  [AAD], [Additional Authenticated Data], [Dữ liệu xác thực bổ sung],
  [ABR], [Area Border Router], [Router biên giữa các vùng trong OSPF],
  [ACL], [Access Control List], [Danh sách kiểm soát truy cập],
  [AES], [Advanced Encryption Standard], [Tiêu chuẩn mã hóa nâng cao],
  [API], [Application Programming Interface], [Giao diện lập trình ứng dụng],
  [ARP], [Address Resolution Protocol], [Giao thức phân giải địa chỉ IPv4 sang địa chỉ MAC],
  [AS], [Autonomous System], [Hệ thống tự trị trong định tuyến],
  [ASBR], [Autonomous System Boundary Router], [Router biên hệ tự trị trong OSPF],
  [BGP], [Border Gateway Protocol], [Giao thức định tuyến liên miền],
  [CAMS], [Centralized Automation and Monitoring System], [Hệ thống tự động hóa và giám sát tập trung],
  [CDP], [Cisco Discovery Protocol], [Giao thức khám phá thiết bị của Cisco],
  [CLI], [Command-Line Interface], [Giao diện dòng lệnh],
  [CRUD], [Create, Read, Update, Delete], [Nhóm thao tác cơ bản trên dữ liệu],
  [DAI], [Dynamic ARP Inspection], [Kiểm tra tính hợp lệ của gói tin ARP],
  [DCIM], [Data Center Infrastructure Management], [Quản lý hạ tầng trung tâm dữ liệu],
  [DEK], [Data Encryption Key], [Khóa mã hóa dữ liệu],
  [DHCP], [Dynamic Host Configuration Protocol], [Giao thức cấp phát cấu hình IP động],
  [DNS], [Domain Name System], [Hệ thống phân giải tên miền],
  [DPAPI], [Data Protection Application Programming Interface], [Giao diện bảo vệ dữ liệu trên Windows],
  [EIGRP], [Enhanced Interior Gateway Routing Protocol], [Giao thức định tuyến cổng nội bộ nâng cao],
  [ERD], [Entity–Relationship Diagram], [Sơ đồ thực thể – quan hệ trong thiết kế cơ sở dữ liệu],
  [FHRP], [First Hop Redundancy Protocol], [Giao thức mạng cung cấp tính năng dự phòng cho default gateway],
  [GCM], [Galois/Counter Mode], [Chế độ mã hóa xác thực AES-GCM],
  [GLBP], [Gateway Load Balancing Protocol], [Giao thức dự phòng gateway kết hợp cân bằng tải của Cisco],
  [GRE], [Generic Routing Encapsulation], [Giao thức đóng gói đường hầm mạng],
  [GUI], [Graphical User Interface], [Giao diện đồ họa người dùng],
  [HSM], [Hardware Security Module], [Mô-đun bảo mật phần cứng],
  [HSRP], [Hot Standby Router Protocol], [Giao thức dự phòng gateway của Cisco, kết hợp nhiều router vật lý thành một router ảo duy nhất],
  [IaC], [Infrastructure as Code], [Quản lý hạ tầng bằng mã],
  [ICMP], [Internet Control Message Protocol], [Giao thức kiểm soát bản tin Internet],
  [IOS], [Internetwork Operating System], [Hệ điều hành mạng của thiết bị Cisco],
  [IPAM], [IP Address Management], [Quản lý địa chỉ IP],
  [IPC], [Inter-Process Communication], [Giao tiếp giữa các tiến trình],
  [ISP], [Internet Service Provider], [Nhà cung cấp dịch vụ Internet],
  [JSON], [JavaScript Object Notation], [Định dạng trao đổi dữ liệu nhẹ dạng văn bản],
  [LACP], [Link Aggregation Control Protocol], [Giao thức điều khiển gom kênh liên kết],
  [LAN], [Local Area Network], [Mạng cục bộ],
  [LLDP], [Link Layer Discovery Protocol], [Giao thức khám phá ở lớp liên kết],
  [LSA], [Link State Advertisement], [Gói quảng bá trạng thái liên kết trong OSPF],
  [MAC], [Media Access Control], [Địa chỉ điều khiển truy cập phương tiện Lớp 2],
  [NAT], [Network Address Translation], [Biên dịch địa chỉ mạng],
  [NETCONF], [Network Configuration Protocol], [Giao thức cấu hình mạng theo mô hình dữ liệu],
  [NTP], [Network Time Protocol], [Giao thức đồng bộ thời gian qua mạng],
  [OSPF], [Open Shortest Path First], [Giao thức định tuyến chọn đường ngắn nhất],
  [PAgP], [Port Aggregation Protocol], [Giao thức gom cổng độc quyền của Cisco],
  [PAT], [Port Address Translation], [Biên dịch địa chỉ theo cổng, còn gọi là NAT Overload],
  [QML], [QML (ngôn ngữ khai báo của Qt)], [Ngôn ngữ mô tả giao diện khai báo Qt Quick],
  [RESTCONF], [RESTCONF Protocol], [Giao thức quản trị dữ liệu YANG qua HTTP bảo mật],
  [RSTP], [Rapid Spanning Tree Protocol], [Giao thức cây bao trùm hội tụ nhanh],
  [SFTP], [SSH File Transfer Protocol], [Giao thức truyền tệp an toàn qua SSH],
  [SHA], [Secure Hash Algorithm], [Thuật toán băm an toàn],
  [SMTP], [Simple Mail Transfer Protocol], [Giao thức chuyển thư điện tử],
  [SSH], [Secure Shell], [Giao thức truy cập từ xa có mã hóa],
  [STP], [Spanning Tree Protocol], [Giao thức cây bao trùm chống vòng lặp L2],
  [SVI], [Switch Virtual Interface], [Cổng ảo Lớp 3 trên thiết bị Switch],
  [TCP], [Transmission Control Protocol], [Giao thức truyền tải hướng kết nối],
  [TLS], [Transport Layer Security], [Bảo mật tầng truyền tải],
  [TPM], [Trusted Platform Module], [Mô-đun nền tảng tin cậy],
  [TTL], [Time To Live], [Thời gian sống của gói tin IP],
  [UDP], [User Datagram Protocol], [Giao thức truyền tải không kết nối],
  [VLAN], [Virtual Local Area Network], [Mạng cục bộ ảo Lớp 2],
  [VPC], [Virtual PC], [Nhãn máy trạm ảo trong mô hình; VPCS là chương trình mô phỏng máy trạm],
  [VPCS], [Virtual PC Simulator], [Trình mô phỏng máy trạm dùng trong môi trường thử nghiệm],
  [VRF], [Virtual Routing and Forwarding], [Bảng định tuyến ảo hóa độc lập trên cùng thiết bị],
  [VRRP], [Virtual Router Redundancy Protocol], [Giao thức dự phòng bộ định tuyến ảo do IETF tiêu chuẩn hóa],
  [VTP], [VLAN Trunking Protocol], [Giao thức đồng bộ cấu hình VLAN],
  [YANG], [Yet Another Next Generation], [Ngôn ngữ mô hình hóa dữ liệu quản trị mạng],
)
