#import "../config/commands.typ": front-heading
#import "../config/tables.typ": report-table

#front-heading[DANH MỤC TỪ VIẾT TẮT]

#set par(justify: false)
#table(
  columns: (15%, 35%, 50%),
  align: left + horizon,
  stroke: 0.5pt,
  table.header(
    [*Từ viết tắt*], [*Tên đầy đủ*], [*Ý nghĩa*]
  ),
  [AAD], [Additional Authenticated Data], [Dữ liệu bổ sung cần xác thực],
  [ABR], [Area Border Router], [Bộ định tuyến biên vùng trong OSPF],
  [ACL], [Access Control List], [Danh sách kiểm soát truy cập],
  [AES], [Advanced Encryption Standard], [Tiêu chuẩn mã hóa nâng cao],
  [API], [Application Programming Interface], [Giao diện lập trình ứng dụng],
  [ARP], [Address Resolution Protocol], [Giao thức phân giải địa chỉ IPv4 sang địa chỉ MAC],
  [AS], [Autonomous System], [Hệ thống tự trị trong định tuyến],
  [ASBR], [Autonomous System Boundary Router], [Bộ định tuyến biên hệ tự trị trong OSPF],
  [AVF], [Active Virtual Forwarder], [Thiết bị chuyển tiếp ảo đang hoạt động trong GLBP],
  [AVG], [Active Virtual Gateway], [Thiết bị quản lý cổng ảo đang hoạt động trong GLBP],
  [BDR], [Backup Designated Router], [Bộ định tuyến được chỉ định dự phòng trong OSPF],
  [BGP], [Border Gateway Protocol], [Giao thức định tuyến liên miền],
  [CAMS], [Centralized Automation and Monitoring System], [Hệ thống quản lý tập trung, tự động hóa cấu hình và giám sát],
  [CDP], [Cisco Discovery Protocol], [Giao thức khám phá thiết bị của Cisco],
  [CIDR], [Classless Inter-Domain Routing], [Định tuyến liên miền không phân lớp],
  [CLI], [Command-Line Interface], [Giao diện dòng lệnh],
  [CPU], [Central Processing Unit], [Bộ xử lý trung tâm],
  [CRUD], [Create, Read, Update, Delete], [Nhóm thao tác cơ bản trên dữ liệu],
  [DAI], [Dynamic ARP Inspection], [Kiểm tra tính hợp lệ của gói tin ARP],
  [DCIM], [Data Center Infrastructure Management], [Quản lý hạ tầng trung tâm dữ liệu],
  [DEK], [Data Encryption Key], [Khóa mã hóa dữ liệu],
  [DHCP], [Dynamic Host Configuration Protocol], [Giao thức cấp phát cấu hình IP động],
  [DNS], [Domain Name System], [Hệ thống phân giải tên miền],
  [DPAPI], [Data Protection Application Programming Interface], [Giao diện bảo vệ dữ liệu trên Windows],
  [DR], [Designated Router], [Bộ định tuyến được chỉ định trong OSPF],
  [EIGRP], [Enhanced Interior Gateway Routing Protocol], [Giao thức định tuyến cổng nội bộ nâng cao],
  [ERD], [Entity–Relationship Diagram], [Sơ đồ thực thể – quan hệ trong thiết kế cơ sở dữ liệu],
  [FHRP], [First Hop Redundancy Protocol], [Nhóm giao thức dự phòng chặng đầu cho cổng mặc định],
  [FK], [Foreign Key], [Khóa ngoại trong cơ sở dữ liệu quan hệ],
  [GCM], [Galois/Counter Mode], [Chế độ mã hóa xác thực AES-GCM],
  [GLBP], [Gateway Load Balancing Protocol], [Giao thức dự phòng cổng mặc định kết hợp cân bằng tải của Cisco],
  [GRE], [Generic Routing Encapsulation], [Giao thức đóng gói đường hầm mạng],
  [GUI], [Graphical User Interface], [Giao diện đồ họa người dùng],
  [HKDF], [HMAC-based Extract-and-Expand Key Derivation Function], [Hàm dẫn xuất khóa dựa trên HMAC],
  [HSM], [Hardware Security Module], [Mô-đun bảo mật phần cứng],
  [HSRP], [Hot Standby Router Protocol], [Giao thức dự phòng cổng mặc định của Cisco],
  [HTML], [HyperText Markup Language], [Ngôn ngữ đánh dấu siêu văn bản],
  [HTTP], [HyperText Transfer Protocol], [Giao thức truyền tải siêu văn bản],
  [IaC], [Infrastructure as Code], [Quản lý hạ tầng bằng mã],
  [ICMP], [Internet Control Message Protocol], [Giao thức kiểm soát bản tin Internet],
  [IEEE], [Institute of Electrical and Electronics Engineers], [Viện Kỹ sư Điện và Điện tử],
  [IETF], [Internet Engineering Task Force], [Lực lượng chuyên trách về kỹ thuật Internet],
  [IOS], [Internetwork Operating System], [Hệ điều hành mạng của thiết bị Cisco],
  [IP], [Internet Protocol], [Giao thức Internet],
  [IPAM], [IP Address Management], [Quản lý địa chỉ IP],
  [IPC], [Inter-Process Communication], [Giao tiếp giữa các tiến trình],
  [ISP], [Internet Service Provider], [Nhà cung cấp dịch vụ Internet],
  [JSON], [JavaScript Object Notation], [Định dạng trao đổi dữ liệu nhẹ dạng văn bản],
  [LACP], [Link Aggregation Control Protocol], [Giao thức điều khiển gom kênh liên kết],
  [LAN], [Local Area Network], [Mạng cục bộ],
  [LLDP], [Link Layer Discovery Protocol], [Giao thức khám phá ở lớp liên kết],
  [LSA], [Link State Advertisement], [Gói quảng bá trạng thái liên kết trong OSPF],
  [MAC], [Media Access Control], [Địa chỉ điều khiển truy cập phương tiện Lớp 2],
  [MSTP], [Multiple Spanning Tree Protocol], [Giao thức nhiều cây bao trùm],
  [NAT], [Network Address Translation], [Chuyển đổi địa chỉ mạng],
  [NCM], [Network Configuration Manager], [Hệ thống quản lý cấu hình mạng],
  [NETCONF], [Network Configuration Protocol], [Giao thức cấu hình mạng theo mô hình dữ liệu],
  [NIST], [National Institute of Standards and Technology], [Viện Tiêu chuẩn và Công nghệ Quốc gia Hoa Kỳ],
  [NTP], [Network Time Protocol], [Giao thức đồng bộ thời gian qua mạng],
  [NTTP/1], [Giao thức nội bộ NTTP, phiên bản 1], [Giao thức điều khiển giữa CAMS và tiến trình đầu cuối đồng hành],
  [OSPF], [Open Shortest Path First], [Giao thức định tuyến chọn đường ngắn nhất],
  [PAgP], [Port Aggregation Protocol], [Giao thức gom cổng độc quyền của Cisco],
  [PAT], [Port Address Translation], [Chuyển đổi địa chỉ theo cổng, còn gọi là NAT quá tải],
  [PK], [Primary Key], [Khóa chính trong cơ sở dữ liệu quan hệ],
  [POSIX], [Portable Operating System Interface], [Chuẩn giao diện hệ điều hành khả chuyển],
  [PRI], [Priority], [Giá trị ưu tiên của bản tin Syslog],
  [QML], [QML (ngôn ngữ khai báo của Qt)], [Ngôn ngữ mô tả giao diện khai báo Qt Quick],
  [RAM], [Random Access Memory], [Bộ nhớ truy cập ngẫu nhiên],
  [RANCID], [Really Awesome New Cisco confIg Differ], [Công cụ sao lưu và theo dõi thay đổi cấu hình mạng],
  [RESTCONF], [RESTCONF Protocol], [Giao thức quản trị dữ liệu YANG qua HTTP bảo mật],
  [RFC], [Request for Comments], [Tài liệu tiêu chuẩn và đặc tả kỹ thuật Internet],
  [RSTP], [Rapid Spanning Tree Protocol], [Giao thức cây bao trùm hội tụ nhanh],
  [RTT], [Round-Trip Time], [Thời gian khứ hồi],
  [SCP], [Secure Copy Protocol], [Giao thức sao chép tệp an toàn qua SSH],
  [SFTP], [SSH File Transfer Protocol], [Giao thức truyền tệp an toàn qua SSH],
  [SHA], [Secure Hash Algorithm], [Thuật toán băm an toàn],
  [SMTP], [Simple Mail Transfer Protocol], [Giao thức truyền thư điện tử],
  [SQL], [Structured Query Language], [Ngôn ngữ truy vấn có cấu trúc],
  [SSH], [Secure Shell], [Giao thức truy cập từ xa có mã hóa],
  [STP], [Spanning Tree Protocol], [Giao thức cây bao trùm chống vòng lặp L2],
  [SVI], [Switch Virtual Interface], [Giao diện ảo Lớp 3 trên bộ chuyển mạch],
  [TCP], [Transmission Control Protocol], [Giao thức truyền tải hướng kết nối],
  [TLS], [Transport Layer Security], [Giao thức bảo mật tầng truyền tải],
  [TPM], [Trusted Platform Module], [Mô-đun nền tảng tin cậy],
  [TTL], [Time To Live], [Thời gian sống của gói tin IP],
  [UDP], [User Datagram Protocol], [Giao thức truyền tải không kết nối],
  [VLAN], [Virtual Local Area Network], [Mạng cục bộ ảo Lớp 2],
  [VPC], [Virtual PC], [Nhãn máy trạm ảo trong mô hình; VPCS là chương trình mô phỏng máy trạm],
  [VPCS], [Virtual PC Simulator], [Trình mô phỏng máy trạm dùng trong môi trường thử nghiệm],
  [VRF], [Virtual Routing and Forwarding], [Bảng định tuyến ảo hóa độc lập trên cùng thiết bị],
  [VRRP], [Virtual Router Redundancy Protocol], [Giao thức dự phòng bộ định tuyến ảo do IETF tiêu chuẩn hóa],
  [VTP], [VLAN Trunking Protocol], [Giao thức đồng bộ cấu hình VLAN],
  [XML], [Extensible Markup Language], [Ngôn ngữ đánh dấu mở rộng],
  [YANG], [Yet Another Next Generation], [Ngôn ngữ mô hình hóa dữ liệu quản trị mạng],
  [ZIP], [ZIP Archive Format], [Định dạng tệp lưu trữ nén],
)
