"""Rule definitions based on CIS Cisco IOS Benchmark & NSA Router Guidelines."""

from __future__ import annotations

from .models import AuditCategory, AuditRuleDefinition, AuditSeverity

ALL_RULES: tuple[AuditRuleDefinition, ...] = (
    AuditRuleDefinition(
        id="AUTH-01",
        title="Sử dụng enable secret thay vì enable password",
        category=AuditCategory.AUTH.value,
        severity=AuditSeverity.CRITICAL.value,
        description="Mật khẩu đặc quyền (Privileged EXEC) phải được bảo vệ bằng lệnh 'enable secret'.",
        rationale="Lệnh 'enable password' lưu mật khẩu dạng rõ hoặc mã hóa yếu dễ giải mã; 'enable secret' dùng thuật toán băm một chiều an toàn.",
        remediation="enable secret <mat_khau_manh>\nno enable password",
        weight=15,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="AUTH-02",
        title="Kích hoạt mã hóa mật khẩu dịch vụ",
        category=AuditCategory.AUTH.value,
        severity=AuditSeverity.MEDIUM.value,
        description="Phải bật 'service password-encryption' để che giấu mật khẩu trong cấu hình.",
        rationale="Ngăn chặn người xem cấu hình trực tiếp nhìn thấy mật khẩu dạng rõ trên màn hình.",
        remediation="service password-encryption",
        weight=5,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="AUTH-03",
        title="Tài khoản cục bộ dùng mật khẩu băm an toàn",
        category=AuditCategory.AUTH.value,
        severity=AuditSeverity.HIGH.value,
        description="Tài khoản người dùng cục bộ (username) phải cấu hình 'secret' thay vì 'password'.",
        rationale="Tránh lưu mật khẩu tài khoản người dùng dưới dạng văn bản thuần hoặc mã hóa Type 7 dễ bị bẻ khóa.",
        remediation="username <ten_nguoi_dung> privilege 15 secret <mat_khau>",
        weight=10,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="AUTH-04",
        title="Bắt buộc xác thực trên Console và VTY",
        category=AuditCategory.AUTH.value,
        severity=AuditSeverity.HIGH.value,
        description="Cổng điều khiển Console và VTY phải bật xác thực (login local hoặc AAA).",
        rationale="Thiếu xác thực đăng nhập cho phép bất kỳ ai kết nối cũng có thể chiếm quyền điều khiển thiết bị.",
        remediation="line con 0\n login local\nline vty 0 4\n login local",
        weight=10,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="MGMT-01",
        title="Bắt buộc SSH, cấm Telnet trên đường truyền VTY",
        category=AuditCategory.MGMT.value,
        severity=AuditSeverity.CRITICAL.value,
        description="Đường truyền quản trị từ xa VTY phải cấu hình 'transport input ssh'. Cấm dùng Telnet.",
        rationale="Telnet truyền thông tin xác thực và dữ liệu dạng văn bản rõ qua mạng, tạo cơ hội cho tấn công bắt gói tin (Sniffing/Eavesdropping).",
        remediation="line vty 0 4\n transport input ssh\nline vty 5 15\n transport input ssh",
        weight=15,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="MGMT-02",
        title="Giới hạn IP quản trị từ xa qua access-class",
        category=AuditCategory.MGMT.value,
        severity=AuditSeverity.HIGH.value,
        description="Cổng VTY phải gán Access-list (access-class <ACL> in) để lọc dải IP được phép kết nối.",
        rationale="Ngăn chặn kẻ tấn công từ các dải mạng người dùng hoặc bên ngoài dò quét cổng và tấn công Brute-force.",
        remediation="access-list 10 permit 192.168.122.0 0.0.0.255\nline vty 0 4\n access-class 10 in",
        weight=10,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="MGMT-03",
        title="Cấu hình tự động ngắt phiên rảnh rỗi (Exec Timeout)",
        category=AuditCategory.MGMT.value,
        severity=AuditSeverity.MEDIUM.value,
        description="Cổng Console và VTY phải đặt thời gian chờ 'exec-timeout' hợp lý (tối đa 15 phút).",
        rationale="Ngăn ngừa rủi ro phiên quản trị bị bỏ quên trên máy trạm bị kẻ xấu chiếm quyền sử dụng.",
        remediation="line con 0\n exec-timeout 5 0\nline vty 0 4\n exec-timeout 5 0",
        weight=5,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="MGMT-04",
        title="Cấu hình biểu ngữ cảnh báo pháp lý (Banner MOTD)",
        category=AuditCategory.MGMT.value,
        severity=AuditSeverity.LOW.value,
        description="Thiết bị nên có 'banner motd' hoặc 'banner login' cảnh báo chỉ nhân viên được ủy quyền.",
        rationale="Cung cấp căn cứ pháp lý và cảnh báo răn đe đối với hành vi truy cập trái phép.",
        remediation="banner motd # CANH BAO: He thong chi danh cho nhan vien duoc uy quyen! #",
        weight=3,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="HARD-01",
        title="Vô hiệu hóa máy chủ HTTP không mã hóa",
        category=AuditCategory.HARDENING.value,
        severity=AuditSeverity.MEDIUM.value,
        description="Phải cấu hình 'no ip http server' trên thiết bị.",
        rationale="Dịch vụ Web HTTP dạng rõ truyền tải phiên quản trị không mã hóa và có nhiều nguy cơ lộ lỗ hổng.",
        remediation="no ip http server",
        weight=5,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="HARD-02",
        title="Vô hiệu hóa định tuyến nguồn IP (IP Source Route)",
        category=AuditCategory.HARDENING.value,
        severity=AuditSeverity.MEDIUM.value,
        description="Phải cấu hình 'no ip source-route'.",
        rationale="Định tuyến nguồn cho phép gói tin tự ấn định lộ trình qua mạng, có thể lẩn tránh các cơ chế lọc an ninh của tường lửa/ACL.",
        remediation="no ip source-route",
        weight=5,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="HARD-03",
        title="Vô hiệu hóa Proxy ARP",
        category=AuditCategory.HARDENING.value,
        severity=AuditSeverity.LOW.value,
        description="Khuyến nghị cấu hình 'no ip proxy-arp' trên các cổng Layer 3.",
        rationale="Proxy ARP tiềm ẩn nguy cơ bị lợi dụng trong các kịch bản Man-in-the-Middle và làm cạn kiệt bảng ARP.",
        remediation="interface <cong>\n no ip proxy-arp",
        weight=3,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="LOG-01",
        title="Cấu hình máy chủ Syslog giám sát tập trung",
        category=AuditCategory.LOGGING.value,
        severity=AuditSeverity.HIGH.value,
        description="Thiết bị phải cấu hình 'logging host' chuyển tiếp nhật ký về hệ thống giám sát tập trung.",
        rationale="Nhật ký lưu cục bộ trên RAM thiết bị sẽ mất khi khởi động lại; Syslog tập trung là điều kiện tiên quyết để phát hiện vi phạm.",
        remediation="logging host 192.168.122.1 transport udp port 5514\nlogging trap notifications\nlogging source-interface GigabitEthernet0/0",
        weight=10,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="LOG-02",
        title="Bật mốc thời gian mili-giây cho nhật ký sự kiện",
        category=AuditCategory.LOGGING.value,
        severity=AuditSeverity.MEDIUM.value,
        description="Phải cấu hình 'service timestamps log datetime msec'.",
        rationale="Độ chính xác mili-giây giúp sắp xếp và đối chiếu chính xác chuỗi hành vi tấn công khi điều tra an ninh.",
        remediation="service timestamps log datetime msec",
        weight=5,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="LOG-03",
        title="Bật số thứ tự bản tin nhật ký (Sequence Numbers)",
        category=AuditCategory.LOGGING.value,
        severity=AuditSeverity.LOW.value,
        description="Phải cấu hình 'service sequence-numbers'.",
        rationale="Giúp kiểm tra tính toàn vẹn của chuỗi log, phát hiện việc bị thất thoát gói UDP hoặc kẻ tấn công xóa log.",
        remediation="service sequence-numbers",
        weight=3,
        applicable_roles=("rou", "sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="L2-01",
        title="Kích hoạt Port Security trên các cổng Access",
        category=AuditCategory.L2_SECURITY.value,
        severity=AuditSeverity.HIGH.value,
        description="Các cổng truy cập người dùng (Access Switchport) phải được bảo vệ bằng Port Security.",
        rationale="Chống tấn công tràn bảng MAC (MAC Flooding Attack) và ngăn cấm người dùng tự ý cắm thiết bị lạ vào cổng mạng.",
        remediation="interface <cong>\n switchport mode access\n switchport port-security\n switchport port-security maximum 2\n switchport port-security violation shutdown\n switchport port-security mac-address sticky",
        weight=10,
        applicable_roles=("sw2", "sw3"),
    ),
    AuditRuleDefinition(
        id="L2-02",
        title="Kích hoạt DHCP Snooping chống máy chủ DHCP giả mạo",
        category=AuditCategory.L2_SECURITY.value,
        severity=AuditSeverity.HIGH.value,
        description="Switch phải bật 'ip dhcp snooping' và cấu hình theo danh sách VLAN hoạt động.",
        rationale="Ngăn chặn kẻ tấn công cắm DHCP Server giả mạo (Rogue DHCP) để đầu độc cấu hình mạng và thực hiện nghe lén MiTM.",
        remediation="ip dhcp snooping\nip dhcp snooping vlan 10,20\ninterface <cong_uplink>\n ip dhcp snooping trust",
        weight=10,
        applicable_roles=("sw2", "sw3"),
    ),
)
